namespace: prod
tag: 32c687dcf278a4d634920191bbf1e3765454d688

wavefront:
  url: https://wavefront.surf
  apiToken: 2e41f7cf-1111-2222-3333-7397a56113ca

vets-db-mysql:
  auth:
    database: service_instance_db

visits-db-mysql:
  auth:
    database: service_instance_db

customers-db-mysql:
  auth:
    database: service_instance_db

apiGateway:
  labels:
    app: api-gateway
  name: api-gateway
  selector:
    app: api-gateway
  service:
    port: 80
    targetPort: 8080
    type: LoadBalancer
  replicaCount: 1
  image: mehdilucasammar/spring-petclinic-cloud-api-gateway
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  containerPort: 8080

customersService:
  labels:
    app: customers-service
  name: customers-service
  selector:
    app: customers-service
  service:
    port: 8080
    targetPort: 8080
  replicaCount: 1
  image: mehdilucasammar/spring-petclinic-cloud-customers-service
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  datasource:
    url: jdbc:mysql://petclinic-customers-db-mysql.prod.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db
    username: root
    secretName: petclinic-customers-db-mysql
    secretKey: mysql-root-password

vetsService:
  labels:
    app: vets-service
  name: vets-service
  selector:
    app: vets-service
  service:
    port: 8080
    targetPort: 8080
  replicaCount: 1
  image: mehdilucasammar/spring-petclinic-cloud-vets-service
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  datasource:
    url: jdbc:mysql://petclinic-vets-db-mysql.prod.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db
    username: root
    secretName: petclinic-vets-db-mysql
    secretKey: mysql-root-password

visitsService:
  labels:
    app: visits-service
  name: visits-service
  selector:
    app: visits-service
  replicaCount: 1
  image: mehdilucasammar/spring-petclinic-cloud-visits-service
  service:
    port: 8080
    targetPort: 8080
  resources:
    limits:
      memory: 1Gi
      cpu: 200m
    requests:
      memory: 1Gi
      cpu: 200m
  datasource:
    url: jdbc:mysql://petclinic-visits-db-mysql.prod.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db
    username: root    
    secretName: petclinic-visits-db-mysql
    secretKey: mysql-root-password
