apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.apiGateway.labels.app }}
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.apiGateway.service.port }}
    targetPort: {{ .Values.apiGateway.service.targetPort }}
  selector:
    app: {{ .Values.apiGateway.selector.app }}
  type: {{ .Values.apiGateway.service.type }}
status:
  loadBalancer: {}
