apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.customersService.labels.app }}
  name: {{ .Values.customersService.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.customersService.service.port }}
    targetPort: {{ .Values.customersService.service.targetPort }}
  selector:
    app: {{ .Values.customersService.selector.app }}
status:
  loadBalancer: {}
