apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  wavefront-url: {{ .Values.wavefront.url | b64enc }}
  wavefront-api-token: {{ .Values.wavefront.apiToken | b64enc }}
